### ISSUE TITLE
Offset is not as negative value

### ISSUE THREAD

**Issue by patelsandeep** [alopatindev/sync-audio-tracks#1]
I have 2 files. 1 video file (converted `badAudio.wav`) and 2nd audio file (`goodAudio.wav`). badAudio.wav have some offset time of **20 seconds**.

I am passing this `goodAudio.wav` as 1st parameter and `badAudio.wav` as 2nd parameter. The offset is as expected. (**20 seconds**)

Now, I have scenario where I am passing that badAudio.wav as 1st parameter and goodAudio.wav as 2nd parameter. Now the problem is the offset is same. I was expecting **-20 seconds.**

So, Is this possible?

**Comment by alopatindev** [comment]
Thanks for noticing! It's a known issue, I've probably just fixed it. Please check it. Thanks!

**Comment by patelsandeep** [comment]
@alopatindev This is what I wanted. It works now. Thanks
