### ISSUE TITLE
sox FAIL formats: no handler for file extension `mp4'

### ISSUE THREAD

**Issue by sandeeppatel1986** [alopatindev/sync-audio-tracks#2]
I have `.mp4` file and a `.wav` file. 

I am passing `.mp4` as good file and `.wav` as bad file. I am getting correct offset value.
But, `out.wav` is not getting generated and I am getting this error.

`sox FAIL formats: no handler for file extension 'mp4'`

So, what are the supported formats for sync audio/video?

**Comment by alopatindev** [comment]
At least WAV, FLAC and Ogg Vorbis work for me.

Boring details:
- SoX is used to read good file and to write output. So everything that SoX can read should work for good file, everything that SoX can write — should work for output file (see `sox --help-format all`)
- both good and bad files are also read by ffmpeg. So everything that ffmpeg can read is supported (see `ffmpeg -formats` and `ffmpeg -codecs`)
